export const USER_HOME_REQUEST = "USER_HOME_REQUEST";
export const USER_HOME_SUCCESS = "USER_HOME_SUCCESS";
export const USER_HOME_FAIL = "USER_HOME_FAIL";

export const FIND_USER_REQUEST = "FIND_USER_REQUEST";
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
export const FIND_USER_FAIL = "FIND_USER_FAIL";

export const USER_SIGNUP_REQUEST  = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS  = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL  = "USER_SIGNUP_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGIN_UPDATE = " USER_LOGIN_UPDATE"
export const USER_LOGOUT = "USER_LOGOUT";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

export const CURRENT_CHAT_REQUEST ="CURRENT_CHAT_REQUEST";
export const CURRENT_CHAT_SUCCESS ="CURRENT_CHAT_SUCCESS"
export const CURRENT_CHAT_FAIL ="CURRENT_CHAT_FAIL"

export const SET_CURRENT_CHAT ="SET_CURRENT_CHAT";
export const UPDATE_CURRENT_CHAT ="UPDATE_CURRENT_CHAT"

export const GET_NOTIFICATION_REQUSET = "GET_NOTIFICATION_REQUSET";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";


export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const UPDATE_ONLINE_USERS = "UPDATE_ONLINE_USERS";

export const SET_MESSAGE_REQUEST = "SET_MESSAGE_REQUEST";
export const SET_MESSAGES = "SET_MESSAGES";
export const UPDATE_MESSAGES ="UPDATE_MESSAGES";


export const CURRENT_CHAT_USER_DETAILS_REQUEST = "CURRENT_CHAT_USER_DETAILS_REQUEST";
export const CURRENT_CHAT_USER_DETAILS_SUCCESS = "CURRENT_CHAT_USER_DETAILS_SUCCESS";
export const CURRENT_CHAT_USER_DETAILS_FAIL = "CURRENT_CHAT_USER_DETAILS_FAIL";

export const SET_SOCKET_SEND_MESSAGE = "SET_SOCKET_SEND_MESSAGE";

export const SET_SELECTED_USER = "SET_SELECTED_USER";

export const GET_CALLS_REQUEST = "GET_CALLS_REQUEST";
export const GET_CALLS_SUCCESS = "GET_CALLS_SUCCESS";
export const GET_CALLS_FAIL = "GET_CALLS_FAIL";

